apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cht-test-gitops-kust
  name: flask
spec:
  template:
    spec:
      containers:
      - name: flask
        image: demoyuw/flask-api:develop
