apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
commonLabels:
  environment: dev
commonAnnotations:
  created_by: yuweichou
patches:
- image-tag.yaml 

