apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-flux
resources:
- ../../base
namePrefix: dev-
commonLabels:
  environment: dev
commonAnnotations:
  created_by: yuweichou
patchesStrategicMerge:
- image-tag.yaml