apiVersion: v1
kind: Service
metadata:
  namespace: cht-test-gitops-kust
  name: flask-service
  labels: 
    app: flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - name: apiport
      protocol: TCP
      port: 10009

